- name: DevBox
  hosts: all
  roles:
    - { role: joshualund.golang, become: true }
  tasks:
    - include: install.yml
      become: true

    - name: mark VM as vagrant devbox
      file: path=/vagrant_devbox state=touch
      become: true

    - name: install /etc/motd
      # we don't clobber /etc/motd on 'real' systems,
      # but for vagrant VM it's ok
      copy: src=files/motd dest=/etc
      become: true

    - include: install_vagrant.yml
    - include: user_devenv.yml
