---
- name: DevBox
  hosts: all
  roles:
    - { role: joshualund.golang, become: true }
  environment:
    # PATH: "/home/vagrant/go-tools/bin:{{ ansible_env.PATH }}"
    # fixme
    PATH: "/home/vagrant/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/go/bin"
    GOPATH: "/home/vagrant/go-tools"

  tasks:
    - include: resizefs.yml
      become: true

    - include: install.yml
      become: true

    - name: make directory structure for source tree
      file: path=/home/vagrant/work/kubernetes/src/k8s.io state=directory

    - name: make go-tools directory
      file: path=/home/vagrant/go-tools state=directory mode=0755

    - name: check for vagrant libvirt plugin
      shell: "vagrant plugin list|grep -q vagrant-libvirt"
      register: libvirt_plugin_check_result
      ignore_errors: True
      changed_when: False

    - name: install libvirt plugin
      shell: vagrant plugin install vagrant-libvirt
      when: libvirt_plugin_check_result|failed

    - name: install go tools
      shell: "go get -u {{ item }}"
      args:
        creates: "/home/vagrant/go-tools/src/{{ item }}"
      with_items:
        - github.com/tools/godep
        - github.com/nsf/gocode
        - github.com/rogpeppe/godef
        - github.com/golang/lint/golint
        - golang.org/x/tools/cmd/oracle

    - name: Set GOPATH in .bashrc
      lineinfile: "dest=/home/vagrant/.bashrc regexp='^export GOPATH' line='export GOPATH=$HOME/work/kubernetes'"

    - name: Set PATH in .bashrc
      lineinfile: "dest=/home/vagrant/.bashrc regexp='^export PATH' line='export PATH=$HOME/go-tools/bin:$HOME/work/kubernetes/bin:$PATH'"

    - name: check out k8s source tree
      git: repo=git@github.com:ivan4th/kubernetes.git dest=/home/vagrant/work/kubernetes/src/k8s.io/kubernetes update=no accept_hostkey=true

    - name: fix perms on k8s source tree
      file: path=/home/vagrant/work/kubernetes/src/k8s.io/kubernetes owner=vagrant group=vagrant recurse=yes
