---
- name: DevBox
  hosts: all
  roles:
    - joshualund.golang
  environment:
    # PATH: "/home/vagrant/go-tools/bin:{{ ansible_env.PATH }}"
    # fixme
    PATH: "/home/vagrant/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/go/bin"
    GOPATH: "/home/vagrant/go-tools"

  tasks:
    - name: configure volume group
      lvg: vg=primary pvs=/dev/vda5,/dev/vdb
      tags: lvm

    - name: resize the logical volume
      lvol: vg=primary lv=root size=+100%FREE
      tags: lvm

    # TBD: http://stackoverflow.com/questions/28088486/ansible-is-it-possible-to-resize-ext4-filesystem
    # make it idempotent
    - name: resize the file system
      command: resize2fs /dev/mapper/primary-root
      tags: lvm

    - name: make directory structure for source tree
      file: path=/home/vagrant/work/kubernetes/src/k8s.io state=directory mode=0755 owner=vagrant group=vagrant

    - name: make go-tools directory
      file: path=/home/vagrant/go-tools state=directory mode=0755 owner=vagrant group=vagrant

      # TBD: update apt cache!
    - name: install dev packages
      apt: "name={{ item }} state=latest"
      with_items:
        - git
        - htop
        - mercurial
        - build-essential
        - libvirt-bin
        - qemu-system
        - qemu-system-x86
        - qemu-kvm
        - libxslt-dev
        - libxml2-dev
        - libvirt-dev
        - zlib1g-dev
        - ruby-dev
        - nfs-kernel-server
        - docker.io
        - screen
      tags: packages

    - name: install fresh vagrant package
      apt: deb=https://releases.hashicorp.com/vagrant/1.8.4/vagrant_1.8.4_x86_64.deb

    - name: check for vagrant libvirt plugin
      shell: "vagrant plugin list|grep -q vagrant-libvirt"
      register: libvirt_plugin_check_result
      become: true
      become_user: vagrant
      ignore_errors: True
      changed_when: False

    - name: install libvirt plugin
      shell: vagrant plugin install vagrant-libvirt
      become: true
      become_user: vagrant
      when: libvirt_plugin_check_result|failed

    - name: add the user to 'docker' group
      user: name=vagrant groups=docker append=yes

    - name: install go tools
      shell: "go get -u {{ item }}"
      args:
        creates: "/home/vagrant/go-tools/src/{{ item }}"
      become: true
      become_user: vagrant
      with_items:
        - github.com/tools/godep
        - github.com/nsf/gocode
        - github.com/rogpeppe/godef
        - github.com/golang/lint/golint
        - golang.org/x/tools/cmd/oracle

    - name: Set GOPATH in .bashrc
      lineinfile: "dest=/home/vagrant/.bashrc regexp='^export GOPATH' line='export GOPATH=$HOME/work/kubernetes'"

    - name: Set PATH in .bashrc
      lineinfile: "dest=/home/vagrant/.bashrc regexp='^export PATH' line='export PATH=$HOME/go-tools/bin:$HOME/work/kubernetes/bin:$PATH'"

    # FIXME: doesn't work due to ssh agent forwarding issues
    # - name: check out k8s source tree
    #   git: repo=git@github.com:ivan4th/kubernetes.git dest=/home/vagrant/work/kubernetes/src/k8s.io/kubernetes update=no accept_hostkey=true
    #   # can't 'become' here due to ssh agent forwarding issues

    # - name: fix perms on k8s source tree
    #   file: path=/home/vagrant/work/kubernetes/src/k8s.io/kubernetes owner=vagrant group=vagrant recurse=yes
