- name: DevBox
  hosts: all
  roles:
    - { role: joshualund.golang, become: true }
  tasks:
    - include: resizefs.yml
      become: true

    - include: install.yml
      become: true

    - name: check for vagrant libvirt plugin
      shell: "vagrant plugin list|grep -q vagrant-libvirt"
      register: libvirt_plugin_check_result
      ignore_errors: True
      changed_when: False

    - name: install libvirt plugin
      shell: vagrant plugin install vagrant-libvirt
      when: libvirt_plugin_check_result|failed

    - name: install /etc/motd
      # we don't clobber /etc/motd on 'real' systems,
      # but for vagrant VM it's ok
      copy: src=files/motd dest=/etc
      become: true

    - name: remove PS1 settings from .bashrc
      # FIXME: use cleaner approach
      replace: dest=/home/vagrant/.bashrc regexp='PS1=.*' replace='true'

    - include: devenv.yml
